FROM python:3.10-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
ENV DJANGO_SETTINGS_MODULE=ecommerce.settings
CMD ["gunicorn", "ecommerce.wsgi:application", "--bind", "0.0.0.0:8000"]